language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python manage.py test apps

deploy:
  provider: heroku
  api_key:
    secure: 04adb859-23c4-4687-b874-506cb00fb5e3
  app: smart-news-app
  on:
    repo: GerardGuerrero/SmartNews
    branch: master
