language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key: 218e2b64-34c4-4e9f-a8b4-ee3b9fd049ac
  app: personal-website-example
  on:
    repo: GerardGuerrero/SmartNews
    branch: master
