version: "3"

services:
  web:
    build: .
    container_name: smartnews
    restart: unless-stopped
    volumes:
      - .:/app
      - /static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: keinos/sqlite3:latest
    container_name: sqlitecontainer
    restart: unless-stopped
    expose:
      - "5432"
