# Generated by Django 3.0.4 on 2020-05-19 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartNewsApp', '0005_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dateModified',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
